## COMMON ##
SEED: 0
USE_CUDA: True
MODEL:
  NAME: Seq2Seq
  KWARGS:
    rnn_type: GRU
    enc_embed_dim: 64
    hidden_size: 256
    dec_embed_dim: 64
    num_layers: 2
    dropout: 0
    bidirectional: True
CKPT_PATH: "g2p/checkpoints/seq2seq.pth"

## TRAIN ##
# turn off tensorboard and don't save checkpoints
SANITY_CHECK: False

# dataset
NUM_DATA: -1
VALIDATE: True

# optimization
BATCH_SIZE: 64
EPOCHS: 50
OPTIMIZER: Adam
LR:
  LR: 0.001
  SCHEDULER: ExponentialLR
  KWARGS:
    gamma: 0.5

## TEST ##
SEARCH:
  ALGO: GreedySearch
  KWARGS:
    limit: 20
