## COMMON ##
USE_CUDA: True
MODEL:
  NAME: Seq2Seq
  KWARGS:
    rnn_type: GRU
    enc_embed_dim: 64
    hidden_size: 256
    dec_embed_dim: 64
    num_layers: 2
    dropout: 0
    bidirectional: True
CKPT_PATH: "g2p/checkpoints/seq2seq.pth"

## TRAIN ##
# random seed
SEED: 0

# dataset
VALIDATE: True

# sanity check with small data
SANITY_CHECK:
  EN: False
  NUM_DATA: 6400

# optimization
BATCH_SIZE: 64
EPOCHS: 50
OPTIMIZER: Adam
LR:
  LR: 0.001
  SCHEDULER: ExponentialLR
  KWARGS:
    gamma: 0.5

## TEST ##
SEARCH:
  ALGO: GreedySearch
  KWARGS:
    limit: 20
